#!/bin/bash

# Paths to the directories where log files are saved
declare -a pathsToLogFileDirectories=("logs")

# Template to use for naming logs (resolved using printf)
logFileBasename="lvas-rename-log.txt"

# The printf template used for timestamps added to log file and config file backup filenames
timestampTemplate="[%(%Y-%m-%d)T]"

# File retention count for log files
logFileRetentionCount=30



# Change directory to the directory where the script is located (filepaths given in this file are checked relative to where "backup" file is located)
cd "$(dirname ${BASH_SOURCE[0]})"



# If any of the log file directories has not been created yet, log an error and exit the script
for pathToLogFilesDirectory in "${pathsToLogFileDirectories[@]}";
do
    if [ ! -d "$pathToLogFilesDirectory" ]; then
        echo "The directory specified by 'pathsToLogFileDirectories=(...$pathToLogFilesDirectory...)' was not found, please ensure '$pathToLogFilesDirectory' exists and re-run script."
        exit 1
    fi
done

# Resolve log file filepaths to absolute paths
declare -a absolutePathsToLogFileDirectories="("$(readlink -f "${pathsToLogFileDirectories[@]}" | awk '{print "\""$0"\""}')")"

# Printf the log file template and write the result to the 'logFileBasenameWithTimestamp' variable
# -1 argument tells printf to default to explicit current date, not shell start time
if [[ $logFileBasename == *"."* ]]; then
    printf -v "logFileBasenameWithTimestamp" ""${logFileBasename%.*}" "$timestampTemplate"."${logFileBasename##*.}"" -1
else
    printf -v "logFileBasenameWithTimestamp" ""$logFileBasename" "$timestampTemplate"" -1
fi



# Directory containing the files to be renamed
targetDirectory="../../downloads/"



subscript="

oldHashFilename=\"\$(basename \"\$1\")\"

dateAndExtension=\"[\${oldHashFilename##*[}\"

escapedDateAndExtension=\"\${dateAndExtension//[/\\\[}\"
escapedDateAndExtension=\"\${escapedDateAndExtension//]/\\\]}\"
escapedDateAndExtension=\"\${escapedDateAndExtension//./\\\.}\"

# Get ID from the .info.json file corresponding to the hash filename
infoJsonFilename=\"\${oldHashFilename%].*}].info.json\"
id=\"\$(cat \"\$infoJsonFilename\" | python3 -c \"import sys, json; print(json.load(sys.stdin)['id'])\")\"

# Create the new filename by removing the date field, and appending the new ID field
newHashFilename=\"\$(basename \"\${oldHashFilename%[*}[\$id]\${oldHashFilename##*]}\")\"

idAndExtension=\"[\${newHashFilename##*[}\"

escapedIdAndExtension=\"\${idAndExtension//[/\\\[}\"
escapedIdAndExtension=\"\${escapedIdAndExtension//]/\\\]}\"
escapedIdAndExtension=\"\${escapedIdAndExtension//./\\\.}\"

# Replace the old filename with the new filename in the hash file
sed -i -e \"s/\${escapedDateAndExtension%\\\.md5*}/\${escapedIdAndExtension%\\\.md5*}/g\" \"\$oldHashFilename\"

# Rename the hash file with the new filename
mv \"\$oldHashFilename\" \"\$newHashFilename\"

# Rename the file the hash file belongs to with the new filename
mv \"\${oldHashFilename%.md5*}\" \"\${newHashFilename%.md5*}\"

"

# ${1%.md5*} removes the LAST instance of ".md5" from a filename

# sed -i -e \"s/\$1/\${1%%].*}]\"

# "${1%].*}]" removes EVERYTHING after the last insance "[." file extension from a filename
# "${1%[*}" removes EVERYTHING after the last instance of "[" (inclusive of the "[" itself) (removes date and extension)
# ".${1##*].}" removes EVERYTHING before the last instance of "]." (inclusive of the "]." itself) (returns extension)

# '.*\[[0-9]+\-[0-9]+\-[0-9]+\].*\.md5' regex matching any .md5 file with a date field preceding the file extension
find "$targetDirectory" \
    -type f \
    \( -regex '.*\[[0-9]+\-[0-9]+\-[0-9]+\].*\.md5' -not -regex '.*\.info\.json.*' \)\
    -execdir bash -c "$subscript" -- "{}" \; \
        2>&1 | ts 2>&1 | tee -a "${absolutePathsToLogFileDirectories[@]/%//$logFileBasenameWithTimestamp}" 2>&1

find "$targetDirectory" \
    -type f \
    -regex '.*\[[0-9]+\-[0-9]+\-[0-9]+\].*\.info\.json\.md5' \
    -execdir bash -c "$subscript" -- "{}" \; \
        2>&1 | ts 2>&1 | tee -a "${absolutePathsToLogFileDirectories[@]/%//$logFileBasenameWithTimestamp}" 2>&1



# Remove oldest log file if log file count is over log file retention count
for pathToLogFilesDirectory in "${absolutePathsToLogFileDirectories[@]}";
do

    # Count number of log files
    logFileCount="$(find "$pathToLogFilesDirectory" -maxdepth 1 -type f -not -name ".gitignore" | wc -l)"

    # If the new number of log files is greater than the log file retention count,
    # Delete the oldest (modified longest ago) files until the count is within limit
    while [ "$logFileCount" -gt "$logFileRetentionCount" ]; do

        # Get oldest log file
        oldestLogFile="$(find "$pathToLogFilesDirectory" \
            -maxdepth 1 \
            -type f \
            -not -name ".gitignore" \
            -printf "%T@ %p\n" \
            | sort -n \
            | cut -d' ' -f 2- \
            | head -n 1)"

        # Remove oldest log file
        rm -v -f "$oldestLogFile" \
            2>&1 | ts 2>&1 | tee -a "${absolutePathsToLogFileDirectories[@]/%//$logFileBasenameWithTimestamp}" 2>&1

        # Decrement log file count
        ((logFileCount--))

    done

done
